version: 2
updates:
- package-ecosystem: pip
  directory: "/source/server"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - M0NsTeRRR
  ignore:
  - dependency-name: twilio
    versions:
    - 6.51.1
    - 6.52.0
    - 6.53.0
    - 6.54.0
    - 6.55.0
    - 6.56.0
  - dependency-name: jinja2
    versions:
    - 2.11.2
- package-ecosystem: pip
  directory: "/source/client"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - M0NsTeRRR
# Check github actions are up to date.
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "04:00"
  assignees:
  - M0NsTeRRR
